#!/usr/bin/env bash

cp chit.sh chit

configFolder=${HOME}/.config/chit
mkdir -p "${configFolder}"
touch "${configFolder}"/current_theme

themeFolder="${configFolder}"/theme_definitions
mkdir -p "${exampleFolder}"
cp theme_definitions "${themeFolder}"


