#!/usr/bin/env bash

cp chit.sh chit

CONFIG_DIR="${HOME}/.config/chit"

# Make necessary directories
mkdir -p "${CONFIG_DIR}"
mkdir -p "${CONFIG_DIR}/theme_definitions"
THEME_EXAMPLE_FOLDER="${CONFIG_DIR}/theme_definitions/examples"
mkdir -p "${THEME_EXAMPLE_FOLDER}"

# Create current_theme file
touch "${configFolder}"/current_theme

# Copy over the example stuff
cp -r theme_definitions/examples/* "${THEME_EXAMPLE_FOLDER}"
